# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_all

xgb_datas, xgb_binaries, xgb_hiddenimports = collect_all(
    "xgboost",
    filter_submodules=lambda name: "testing" not in name,
)

a = Analysis(
    ["launcher.py"],
    pathex=[],
    binaries=xgb_binaries,
    datas=[("src/templates/index.html", "src/templates/")] + xgb_datas,
    hiddenimports=[
        "src",
        "src.api",
        "src.api.backtest_bp",
        "src.api.compare_bp",
        "src.api.core",
        "src.api.helpers",
        "src.api.middleware",
        "src.api.prices_bp",
        "src.api.prices_standalone_bp",
        "src.api.season_bp",
        "src.api.season_v2_bp",
        "src.api.sse",
        "src.api.strategy_bp",
        "src.api.team",
        "src.config",
        "src.data",
        "src.data.cache",
        "src.data.fpl_api",
        "src.data.github_csv",
        "src.data.loader",
        "src.data.season_detection",
        "src.db",
        "src.db.connection",
        "src.db.migrations",
        "src.db.repositories",
        "src.db.schema",
        "src.features",
        "src.features.builder",
        "src.features.fixture_context",
        "src.features.interactions",
        "src.features.opponent_history",
        "src.features.player_rolling",
        "src.features.playerstats",
        "src.features.registry",
        "src.features.rest_congestion",
        "src.features.targets",
        "src.features.team_stats",
        "src.features.upside",
        "src.features.venue_form",
        "src.logging_config",
        "src.ml",
        "src.ml.backtest",
        "src.ml.decomposed",
        "src.ml.model_store",
        "src.ml.multi_gw",
        "src.ml.prediction",
        "src.ml.training",
        "src.paths",
        "src.schemas",
        "src.schemas.fpl_rules",
        "src.schemas.player",
        "src.schemas.prediction",
        "src.season",
        "src.season.dashboard",
        "src.season.fixtures",
        "src.season.manager",
        "src.season.scheduler",
        "src.season.state_machine",
        "src.solver",
        "src.solver.formation",
        "src.solver.squad",
        "src.solver.transfers",
        "src.solver.validator",
        "src.strategy",
        "src.strategy.price_tracker",
        "src.strategy.reactive",
        "src.strategy.transfer_planner",
        "src.utils",
        "src.utils.dataframe_helpers",
        "src.utils.nan_handling",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="GafferAI",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon="Gaffer.icns",
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="GafferAI",
)

app = BUNDLE(
    coll,
    name="GafferAI.app",
    icon="Gaffer.icns",
    bundle_identifier="com.fplmanager.gafferai",
)
